@baseUrl = http://localhost:3333
@authToken = {{auth.response.body.token}}

# @name create_user
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Victor Doretto",
  "email": "victor@gmail.com",
  "password": "123456"
}

###
# @name auth
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "prado.victor@gmail.com",
  "password": "125534"
}

###
# @name me
GET {{baseUrl}}/me
Authorization: Bearer {{authToken}}